apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tg-bot-sessions
  namespace: app
  labels:
    app: tg-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tg-bot-uploads
  namespace: app
  labels:
    app: tg-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
