apiVersion: v1
kind: Service
metadata:
  name: tg-bot
  namespace: app
  labels:
    app: tg-bot
spec:
  selector:
    app: tg-bot
  ports:
    - port: 8004
      targetPort: 8004
      name: http
  type: ClusterIP
