apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: app
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8100
          readinessProbe:
            httpGet:
              path: /
              port: 8100
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8100
            initialDelaySeconds: 15
            periodSeconds: 15
