apiVersion: v1
kind: Service
metadata:
  name: th-bot
  namespace: app
  labels:
    app: th-bot
spec:
  selector:
    app: th-bot
  ports:
    - port: 8011
      targetPort: 8011
      name: http
  type: ClusterIP
