# docker-compose.yml
version: '3.11'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - SCHEDULER_URL=http://scheduler:8001
    networks:
      - monitoring_network

  scheduler:
    build: ./scheduler
    ports:
      - "8001:8001"
    environment:
      - API_GATEWAY_URL=http://api_gateway:8000
    networks:
      - monitoring_network

  user_interface:
    build: back_core
    ports:
      - "8002:8002"
    environment:
      - API_GATEWAY_URL=http://api_gateway:8000
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge