apiVersion: v1
kind: Service
metadata:
  name: wp-bot
  namespace: app
  labels:
    app: wp-bot
spec:
  selector:
    app: wp-bot
  ports:
    - port: 8006
      targetPort: 8006
      name: http
  type: ClusterIP
