apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: app
  labels:
    app: collector
spec:
  selector:
    app: collector
  ports:
    - port: 8009
      targetPort: 8009
      name: http
  type: ClusterIP
